### ISSUE TITLE
How  to do  token to provide the "term path" from a TaxonomyField?

### ISSUE THREAD

**Issue by jiangyo4** [CityofSantaMonica/Orchard.Navigation#2]
Hi,
I'm  new in orchard. 
 I created a Content-Type called product（include 1 taxonomy).
The taxonomy are Category(book,toy,clothing).  after filtering  Category by taxonomy  count  .
 I get  a Count sort by the number  of  product  items.

Now,I  get a query link  menu(book,toy,clothing) in Navigation.
I dont' know  how to attach query link  menu with Content Items(a dynamic menu） ?

How  to do  token to provide the "term path" from a TaxonomyField?
  Thanks!

**Comment by thekaveman** [comment]
Thanks for reaching out @jiangyo4 

I can try to answer the second part of your question, regarding usage of the "term path" token. I'm not totally clear on what you're asking in the first part, but feel free to follow up with more details if you like, and I can try to help out.

Regarding the "term path" token: the idea behind this token was to be able to make a hierarchical URL structure that follows the taxonomy structure. So as you organize content items into a taxonomy, you can have the URL to a specific content item generated using the term hierarchy of the taxonomy.

As an example, assume we have a content part called `ProductPart`, and that part contains a taxonomy field called `Category`. Then assume we attach this part to your `product` content type. Then assume we attach the `AutoroutePart` to your `product` type. We could configure the `AutoroutePart` using the following pattern:

```json
{
  "Name": "Taxonomy-Section-Title",
  "Pattern": "{Content.Fields.ProductPart.Category.TermPath}/{Content.Slug}",
  "Description": "my-taxonomy/my-section/my-subsection/my-product"
}
```

If we create a product with title *New Product*, and select `Category > book` in the taxonomy field, the URL for this product would be generated as 

**`category/book/new-product`**.

Let's say we add another level to the Taxonomy, and under `book` we have `(novel, nonfiction)`. If we select `Category > book > novel` in the taxonomy field of our example product, the URL would be generated as 

**`category/book/novel/new-product`**. 

The addition of `.NoTaxonomy` on the end of the pattern token generates URLs *without* the leading name of the taxonomy. In other words, if we use this configuration instead:

```json
{
  "Name": "Section-Title",
  "Pattern": "{Content.Fields.ProductPart.Category.TermPath.NoTaxonomy}/{Content.Slug}",
  "Description": "my-section/my-subsection/my-product"
}
```

Then selecting taxonomy terms `Category > book > novel` generates the URL 

**`book/novel/new-product`**  
(the Taxonomy's slug is omitted from the beginning of the URL). 

I hope this helps. Let me know if you have any follow up questions.

**Comment by thekaveman** [comment]
Closing. Feel free to reopen this issue or a new one with follow-up questions.
